version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: boxware-db
    environment:
      POSTGRES_DB: boxwareNest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 7077
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - boxware-network

networks:
  boxware-network:
    driver: bridge

volumes:
  postgres_data:
